# Етап 1: білд React
FROM node:18-alpine AS builder

WORKDIR /app

# Копіюємо залежності
COPY package*.json ./
RUN npm install

# Копіюємо ВЕСЬ проєкт (а не тільки src)
COPY . .

# Білдимо React
RUN npm run build


# Етап 2: nginx
FROM nginx:alpine

# Копіюємо білд
COPY --from=builder /app/build /usr/share/nginx/html

# Конфіг nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]